export const localStorageKey = {
  // common
  chatMode: 'chatMode',
  api: 'api',
  localLanguage: 'localLanguage',
  replyLanguage: 'replyLanguage',
  insertType: 'insertType',
  useWordFormatting: 'useWordFormatting',
  useSelectedText: 'useSelectedText',
  agentMaxIterations: 'agentMaxIterations',
  threadId: 'threadId',
  promptDraft: 'promptDraft',
  // official api
  apiKey: 'apiKey',
  model: 'model',
  customModel: 'customModel',
  customModels: 'customModels',
  temperature: 'temperature',
  maxTokens: 'maxTokens',
  basePath: 'basePath',
  // azure api
  azureAPIKey: 'azureAPIKey',
  azureAPIEndpoint: 'azureAPIEndpoint',
  azureDeploymentName: 'azureDeploymentName',
  azureMaxTokens: 'azureMaxTokens',
  azureTemperature: 'azureTemperature',
  azureAPIVersion: 'azureAPIVersion',
  // memorix tool provider
  enableMemorixTools: 'enableMemorixTools',
  mcpProxyHubUrl: 'mcpProxyHubUrl',
  memorixAgentId: 'memorixAgentId',
  memorixToolsEndpoint: 'memorixToolsEndpoint',
  memorixToolsCallEndpoint: 'memorixToolsCallEndpoint',
  memorixToolTimeoutMs: 'memorixToolTimeoutMs',
  memorixMaxRetries: 'memorixMaxRetries',
  // qdrant resources tool provider
  enableQdrantResourcesTools: 'enableQdrantResourcesTools',
  qdrantResourcesAgentId: 'qdrantResourcesAgentId',
  qdrantResourcesToolsEndpoint: 'qdrantResourcesToolsEndpoint',
  qdrantResourcesToolsCallEndpoint: 'qdrantResourcesToolsCallEndpoint',
  qdrantResourcesToolTimeoutMs: 'qdrantResourcesToolTimeoutMs',
  qdrantResourcesMaxRetries: 'qdrantResourcesMaxRetries',
  // docsuite external-reference-only tool provider
  enableDocSuiteReferenceTools: 'enableDocSuiteReferenceTools',
  docSuiteAgentId: 'docSuiteAgentId',
  docSuiteToolsEndpoint: 'docSuiteToolsEndpoint',
  docSuiteToolsCallEndpoint: 'docSuiteToolsCallEndpoint',
  docSuiteToolTimeoutMs: 'docSuiteToolTimeoutMs',
  docSuiteMaxRetries: 'docSuiteMaxRetries',
  telemetryEnabled: 'enableAgentTelemetry',
  telemetryFlushIntervalSeconds: 'agentTelemetryFlushIntervalSeconds',
  telemetryMaxQueueSize: 'agentTelemetryMaxQueueSize',
  telemetryConfigVersion: 'telemetryConfigVersion',
  telemetryRedactSensitive: 'telemetryRedactSensitive',
  // openrouter api
  openrouterAPIKey: 'openrouterAPIKey',
  openrouterBasePath: 'openrouterBasePath',
  openrouterModel: 'openrouterModel',
  openrouterCustomModel: 'openrouterCustomModel',
  openrouterCustomModels: 'openrouterCustomModels',
  openrouterTemperature: 'openrouterTemperature',
  openrouterMaxTokens: 'openrouterMaxTokens',
  // LM Studio API
  lmstudioAPIKey: 'lmstudioAPIKey',
  lmstudioBasePath: 'lmstudioBasePath',
  lmstudioModel: 'lmstudioModel',
  lmstudioCustomModel: 'lmstudioCustomModel',
  lmstudioCustomModels: 'lmstudioCustomModels',
  lmstudioTemperature: 'lmstudioTemperature',
  lmstudioMaxTokens: 'lmstudioMaxTokens',
  // gemini api
  geminiAPIKey: 'geminiAPIKey',
  geminiMaxTokens: 'geminiMaxTokens',
  geminiTemperature: 'geminiTemperature',
  geminiModel: 'geminiModel',
  geminiCustomModel: 'geminiCustomModel',
  geminiCustomModels: 'geminiCustomModels',
  // ollama api
  ollamaEndpoint: 'ollamaEndpoint',
  ollamaModel: 'ollamaModel',
  ollamaTemperature: 'ollamaTemperature',
  ollamaCustomModel: 'ollamaCustomModel',
  ollamaCustomModels: 'ollamaCustomModels',
  // groq api
  groqAPIKey: 'groqAPIKey',
  groqTemperature: 'groqTemperature',
  groqMaxTokens: 'groqMaxTokens',
  groqModel: 'groqModel',
  groqCustomModel: 'groqCustomModel',
  groqCustomModels: 'groqCustomModels',
  // proxy
  enableProxy: 'enableProxy',
  proxy: 'proxy',
  defaultSystemPrompt: 'defaultSystemPrompt',
  defaultPrompt: 'defaultPrompt',
  // hindsight tool provider
  enableHindsightTools: 'enableHindsightTools',
  hindsightBaseUrl: 'hindsightBaseUrl',
  hindsightMemoryBankId: 'hindsightMemoryBankId',
  hindsightApiKey: 'hindsightApiKey',
  hindsightToolTimeoutMs: 'hindsightToolTimeoutMs',
  hindsightMaxRetries: 'hindsightMaxRetries',
} as const
