services:
  word-gpt-plus:
    build: .
    container_name: word-gpt-plus
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production

  word-gpt-plus-proxy:
    build:
      context: ./proxy-server
    container_name: word-gpt-plus-proxy
    ports:
      - "3100:3100"
    volumes:
      - ./word-gpt-plus-logs:/app/data/logs
